name: absensi_mahardika
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  persistent_bottom_nav_bar: ^5.0.2
  ionicons: ^0.2.2
  iconsax: ^0.0.8
  enefty_icons: ^1.0.4
  iconly: ^1.0.1
  qr_code_scanner: ^1.0.0
  simple_animations: ^5.0.2
  email_validator: ^2.1.17
  introduction_screen: ^3.1.11
  google_fonts: ^5.1.0
  contained_tab_bar_view: ^0.8.0
  intl: ^0.18.1
  freezed_annotation: ^2.4.1
  build_runner: ^2.4.6
  freezed: ^2.4.2
  http: ^1.1.0
  dio: ^5.3.2
  device_info_plus: ^4.1.2
  animated_toggle_switch: ^0.8.0
  flutter_switch: ^0.3.2
  get_storage: ^2.1.1
  qr_flutter: ^4.0.0
  mobile_scanner: ^2.1.0
  shimmer: ^3.0.0
  lottie: ^2.6.0
  google_sign_in: ^6.1.5
  googleapis: ^11.4.0
  syncfusion_flutter_calendar: ^23.1.40
  image_picker: ^1.0.4
  scan: ^1.6.0
  camera: ^0.10.5+5
  image_cropper: ^5.0.0
  location: ^5.0.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/lottie/
    - assets/translations/
  uses-material-design: true

  fonts:
    - family: SignikaBold
      fonts:
        - asset: assets/fonts/Signika-Bold.ttf

    - family: SignikaSemi
      fonts:
        - asset: assets/fonts/Signika-SemiBold.ttf

    - family: SignikaRegular
      fonts:
        - asset: assets/fonts/Signika-Regular.ttf

    - family: Signika
      fonts:
        - asset: assets/fonts/Signika-Light.ttf

